### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by simonschaufi**

### CODE REVIEW

**Comment by prathers** [comment]
I'm not a 100% sure, but I think it's the only way to make the localized files available for users to update their language in TYPO3 through Backend Maintenance => Manage Language Packs

**Comment by simonschaufi** [comment]
I'm quite sure that there is a script running from the TYPO3 GmbH that syncs the translations to a place where it can be downloaded from the core. Do other extensions use that pull request?

**Comment by prathers** [comment]
I will investigate and get back to you

**Comment by prathers** [comment]
Can you try to change your crowdin.yaml in root of your repos or through the Crowdin syncronization tab branch configuration?

```
files:
  - source: /Resources/Private/Language/locallang*.xlf
    translation: /Resources/Private/Language/%two_letters_code%.%original_file_name%
```

**Comment by simonschaufi** [comment]
I got the file from here: https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Localization/TranslationServer/Crowdin/Faq.html#crowdin-faq-duplicated-labels

And the file also looks the same here: https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/main/.crowdin.yml

**Pull request closed without merging**
